

# This file was *autogenerated* from the file moduloEval.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2)
load('Hypermatrix_Algebra_tst.sage')

sz = _sage_const_7 ; La = var_list('a', sz); P = sum(La[i]*x**i for i in range(sz))

print(P)

print(ModuloII(P, [x], [x-var('b')]))

Lc = var_list('c', floor(sz/_sage_const_2 )); Q = prod(x-Lc[k] for k in rg(floor(sz/_sage_const_2 )))

print(Q)

print(ModuloII(P, [x], [Q]))

