

# This file was *autogenerated* from the file transformationMonoid.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3)
load('Hypermatrix_Algebra_tst.sage')

sz = _sage_const_3 ; A = HM(sz, sz, 'a')

A.printHM()

transMonoid = prod(sum(A[i,j] for j in range(sz)) for i in range(sz)).expand()

for graph in transMonoid.operands():
	print(graph)
	Monomial2DiGraph(graph, A.list(), sz).plot()

